apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  GITHUB_WEBHOOK_SECRET: "myWebhookSecret_abc123XYZ789"
  GITHUB_APP_ID: "3551327"
  GITHUB_APP_PRIVATE_KEY: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEApnHCmXo9zHN1MoIkzBLgMZD5wMKLJB4gqTLqcmzcA8IRtOck
    IKXMllg5E5s9kmHO2jfIGtHKuaXOmrkS7+NE6YOzN3h6xFi6AhjMCQPScC10VQlp
    PSk8uzLKi33mLIqXzKQdiTO/iCeMt+QkBIlOw/bIE37ntS1Y/q9wkr0wHiEUZwK7
    nThowVkoBp+vazwMzneRQxAgQuUwh8f9VmVlZeVwN66ECTTcillZ3/eAkU/IeT1H
    mj846EDhmBxrwK+50mLAU4xKFmN2jKyt6s/B2DthM6WaddVHaayo311hS7k+/GAd
    VwilinOu+/Da5Ik0L0F6+w/lBIG9ZqQf/Gk6EwIDAQABAoIBAF7VwJgsI1wDiQo/
    RvIT6zOys+sVravlkpx1S0npJq7pe6dEb7w+W8Rp/hNix4FJQ0/oqpZFZKnEhGR6
    AQU3zAL1LD714ZVQLKOXN2IHkHakH314QEM95MGQngE+udA1I2rRM5cCKiZMyovY
    bIE9LujPCo65JxJ/BQ8QLScernTrXoWyfvDqOCh7FWViu04IggDLG0s/ghHZaxU1
    sIdr5nwxLlGzo5J+NkNWRiCAorG7qDOBl25qncsluPavk0zuUnqPiG848q4RaQGM
    GN2xqpb/c2Bdq7gWItoy6kzO9OviDV6vIOgHTuleySRnCtHX5D5XrfhyQZZz7NA2
    4zCX19kCgYEA23qS76i8rjAmb2IyhANGmMjbmMmspfiSuENWUfYDzB48FkfodFdX
    Qsxv3p8a7+Mc9VKwXAnenGCLNCXROe8eagwhSFYyCNZjjpRi5Rrk3GkVlr3baAtJ
    r+OjxbsQkLecZfLGzIpV8qvxIxpp6sdtQyOm+vFoD968dfhZC2ZEvScCgYEAwiQC
    WO06lcgHVQg3t67SKp9SKUHUwLlD4Zn2yf5SGv1jh2zbWnSm+cl0EuWbRRDnrfbG
    Nsc3UWLSgVA0DLuD62hDdrkYIAiql8WTXTvBLxnxu5Iai6py1hRxkigqOPqSYzy5
    vTxV2hYQZRjGtV4hg8NoAyqfjrh3U9a4zb4uBzUCgYEA0Hevo1XpyaXQjBGAm+Wk
    o7B87LX6eDcP3VeQYQ9E8hdxyVQJ1p+zMa6PP6xuYJafReGBxBpXyL7m2eRlxBp9
    EAtvfY7pvX0tWRtWh/iwky55JBI3ma7HEfst7r1M8biFJEyiSVvIYVSyGT6Yhjlg
    bdoqW8b6qcBNz9vRcEN2XRcCgYBPkUqU/8V/FdhLdW7AjZn9dgbKefykcEnt8JhA
    +UbVYPylyGuuixjUT0iPZiNZDzClD/r1AHkflg0IisKKZWAP30+nHP1SQ7sHMSbQ
    k2j90PhOE/dlPpqKOx7A9E05xRiyK3VEpbHaDCj0Bk+KjeXWhwPeKF30tI3TgrGD
    QWrD8QKBgQC0ZDLM8PbdyJyk9Y38MJS5y86BwaQqtqTCmmDbeGjB5JqHyvB+wCtY
    pmO5+vej8T6mnCA9coqnUBF5f3GNRujYfJw4BYYboNlmiL9KhAI0NkcEd/Ey5e5+
    NaBYa7h7HZkDZmTh0yC8vkexIDCnTR9OjZTDl5nmY16AfmwVSamaOw==
    -----END RSA PRIVATE KEY-----  
  OPENAI_API_KEY: "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"
  LANGFUSE_PUBLIC_KEY: "pk-lf-7758d069-6598-44cd-95bc-f1d6c788fdb7"
  LANGFUSE_SECRET_KEY: "sk-lf-4ba4d993-0621-4315-b161-038121653948"
  DATABASE_URL: "postgresql+asyncpg://dbadmin:YourStrongPassword123!@ai-code-reviewer-postgres.cshe84og0h2z.us-east-1.rds.amazonaws.com/codereviewer"

